baseURL = 'https://ayder21.github.io/Siteseo/'
languageCode = 'ru-RU'
title = 'OpenAgent'
theme = 'PaperMod'

defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true

[languages]
  [languages.ru]
    languageName = 'Русский'
    weight = 1
    title = 'OpenAgent (RU)'
    [languages.ru.params]
      description = 'Гайды по AI-агентам, OpenClaw и автоматизации.'
      
  [languages.uz]
    languageName = "Oz'bek"
    weight = 2
    title = 'OpenAgent (UZ)'
    [languages.uz.params]
      description = "Sun'iy intellekt agentlari, OpenClaw va avtomatlashtirish bo'yicha qo'llanmalar."

[params]
  env = 'production'
  title = 'OpenAgent'
  description = 'Блог про AI-агентов'
  author = 'OpenAgent Team'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true
  defaultTheme = 'auto'
  
  [params.assets]
    favicon = '<link / abs url>'
    favicon16x16 = '<link / abs url>'
    favicon32x32 = '<link / abs url>'

[menu]
  [[languages.ru.menu.main]]
    identifier = 'guides'
    name = 'Гайды'
    url = '/ru/posts/guides/'
    weight = 10
  [[languages.ru.menu.main]]
    identifier = 'news'
    name = 'Новости AI'
    url = '/ru/posts/news/'
    weight = 20
    
  [[languages.uz.menu.main]]
    identifier = 'guides'
    name = "Qo'llanmalar"
    url = '/uz/posts/guides/'
    weight = 10
  [[languages.uz.menu.main]]
    identifier = 'news'
    name = 'Yangiliklar'
    url = '/uz/posts/news/'
    weight = 20
